fixup for a144628c57d951acf9d53c21d685d617031f793f
The last solution doesn't work. For some
unknown reason, Kotlin reflection is only
applicable for `data class` fields
with `@JvmField` annotated, thus getting
the `name` and `get` for a field
without `@JvmField`, an exception encounters
(in this case I set `warehouse` field not have `@JvmField`):

```
kotlin.reflect.full.IllegalCallableAccessException: java.lang.IllegalAccessException: Class java.lang.Class<kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter> cannot access private final  field java.lang.String com.czttgd.android.zhijian.data.InspectionForm.warehouse of class java.lang.Class<com.czttgd.android.zhijian.data.InspectionForm>
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:273)
	at com.czttgd.android.zhijian.data.Inspection.post(Inspection.kt:169)
	at com.czttgd.android.zhijian.ui.FormFillingActivity$setUpButton$1$1$1.invokeSuspend(FormFillingActivity.kt:344)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
Caused by: java.lang.IllegalAccessException: Class java.lang.Class<kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter> cannot access private final  field java.lang.String com.czttgd.android.zhijian.data.InspectionForm.warehouse of class java.lang.Class<com.czttgd.android.zhijian.data.InspectionForm>
	at java.lang.reflect.Field.get(Native Method)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter.call(CallerImpl.kt:176)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	... 10 more
```